const bingoData = [
    "Travel to a new country",
    "Host a dinner party",
    "Read 12 books",
    "Go camping",
    "Try a new hobby",
    "Exercise 3x/week for a month",
    "Save a specific amount",
    "Visit a museum",
    "Date night at a fancy place",
    "Cook a complex meal together",
    "Walk 10,000 steps for a week",
    "Watch all Oscar nominees",
    "Volunteer somewhere",
    "Learn a new skill",
    "No takeout for a month",
    "Go to a concert",
    "Plant a garden (or pot)",
    "Digital detox weekend",
    "Write a journal",
    "Call parents weekly",
    "Take a spontaneous trip",
    "Learn a new recipe",
    "Do a puzzle together",
    "Visit a national park"
];
// Note: We need 24 items + 1 free space.
